[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[functions]
  directory = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
